version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./aims.db
      - SECRET_KEY=change_me_in_production
      - ORG_NAME=Demo Organization
      - ORG_API_KEY=demo-api-key-12345
    volumes:
      - ./backend:/app
      - evidence_data:/app/evidence
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  # Optional: PostgreSQL for production
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: aims_db
  #     POSTGRES_USER: aims_user
  #     POSTGRES_PASSWORD: aims_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  evidence_data:
  # postgres_data:

