services:
  - type: web
    name: aims-api
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    plan: starter
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ORG_NAME
        value: On-Chain Labs Governance
      - key: ORG_API_KEY
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false
      - key: EVIDENCE_LOCAL_STORAGE
        value: "false"
      - key: RATE_LIMIT
        value: "60"
      - key: S3_ENDPOINT
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: S3_ACCESS_KEY
        sync: false
      - key: S3_SECRET_KEY
        sync: false
      - key: S3_REGION
        value: auto
      - key: S3_FORCE_PATH_STYLE
        value: "true"
