name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Use a specific Python version

      - name: Install Python dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install ruff pytest pytest-asyncio
        working-directory: ./backend

      - name: Run Python linting (Ruff)
        run: |
          source .venv/bin/activate
          ruff check .
          ruff format . --check
        working-directory: ./backend

      - name: Run Python tests (Pytest)
        run: |
          source .venv/bin/activate
          SECRET_KEY=dev-secret-key-for-development-only pytest backend/tests/test_integration_critical_flows.py
        working-directory: ./

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run Frontend linting
        run: npm run lint
        working-directory: ./frontend

      - name: Run Frontend build
        run: npm run build
        working-directory: ./frontend

      - name: Verify git status is clean
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git diff --staged --exit-code || (echo "::error::Uncommitted changes detected after CI checks. Run lint/format locally." && exit 1)